spring:
  datasource:
    url: jdbc:h2:mem:datadb
    driver-class-name: org.h2.Driver
    username: root
    password: sasa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true